# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_caption',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
